// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebMarkReport.Models;

namespace WebMarkReport.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebMarkReport.Models.FileModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.Property<string>("Path");

                    b.HasKey("Id");

                    b.ToTable("File");
                });

            modelBuilder.Entity("WebMarkReport.Models.MarkReport", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("accept_quantity");

                    b.Property<int>("call_count");

                    b.Property<DateTime>("date");

                    b.Property<DateTime?>("datev2");

                    b.Property<int>("dev_count");

                    b.Property<int>("id_employee");

                    b.Property<int>("id_l1");

                    b.Property<int>("id_l2");

                    b.Property<int>("id_status");

                    b.Property<int>("id_subcontractor");

                    b.Property<int>("id_sublayer1");

                    b.Property<int>("id_technology_card");

                    b.Property<bool>("is_have_ct3");

                    b.Property<bool>("is_only_ct3");

                    b.Property<int>("lag_days_count");

                    b.Property<string>("subcontractor_name");

                    b.Property<string>("technology_card_name");

                    b.HasKey("id");

                    b.ToTable("Reports");
                });

            modelBuilder.Entity("WebMarkReport.Models.Structure", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("id_l1");

                    b.Property<int>("id_l2");

                    b.Property<int>("id_sublayer1");

                    b.Property<string>("l1_name");

                    b.Property<string>("l2_name");

                    b.Property<string>("sublayer1_name");

                    b.HasKey("id");

                    b.ToTable("Structures");
                });
#pragma warning restore 612, 618
        }
    }
}
